import { RawServerConfiguration, ServerConfiguration } from 'common-lib';

export default (raw: RawServerConfiguration): ServerConfiguration => ({
	CAPWATCH_DOWNLOAD_PATH: raw.CAPWATCH_DOWNLOAD_PATH,
	CLIENT_PATH: raw.CLIENT_PATH,
	GOOGLE_KEYS_PATH: raw.GOOGLE_KEYS_PATH,

	DB_HOST: raw.DB_HOST,
	DB_PASSWORD: raw.DB_PASSWORD,
	DB_SCHEMA: raw.DB_SCHEMA,
	DB_USER: raw.DB_USER,
	DB_PORT: parseInt(raw.DB_PORT, 10),
	DB_POOL_SIZE: parseInt(raw.DB_POOL_SIZE, 10),

	NODE_ENV: raw.NODE_ENV,
	PORT: parseInt(raw.PORT, 10),

	DISCORD_CLIENT_TOKEN: raw.DISCORD_CLIENT_TOKEN,

	REMOTE_DRIVE_STORAGE_PATH: raw.REMOTE_DRIVE_STORAGE_PATH,
	REMOTE_DRIVE_HOST: raw.REMOTE_DRIVE_HOST,
	REMOTE_DRIVE_KEY_FILE: raw.REMOTE_DRIVE_KEY_FILE,
	REMOTE_DRIVE_PORT: parseInt(raw.REMOTE_DRIVE_PORT, 10),
	REMOTE_DRIVE_USER: raw.REMOTE_DRIVE_USER,

	AWS_ACCESS_KEY_ID: raw.AWS_ACCESS_KEY_ID,
	AWS_SECRET_ACCESS_KEY: raw.AWS_SECRET_ACCESS_KEY,

	RECAPTCHA_SECRET: raw.RECAPTCHA_SECRET,
});
