version: '3.8'
services:
    tests:
        build:
            context: .
            target: tests
        networks:
            - test-network
        volumes:
            - ./:/usr/evm-plus
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - test-mysql

    watch-server-tests:
        build:
            context: .
            target: tests
        networks:
            - test-network
        volumes:
            - ./:/usr/evm-plus
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - test-mysql
        command: yarn --cwd=packages/server test --watch

    watch-server-common-tests:
        build:
            context: .
            target: tests
        networks:
            - test-network
        volumes:
            - ./:/usr/evm-plus
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - test-mysql
        command: yarn --cwd=packages/server-common test --watch

    watch-client-tests:
        build:
            context: .
            target: tests
        volumes:
            - ./:/usr/evm-plus
        command: yarn --cwd=packages/client test --watch

    test-mysql:
        container_name: evmplus_test-mysql
        image: mysql:8.0.19
        networks:
            - test-network
        expose:
            - '33060'
        environment:
            - MYSQL_ROOT_PASSWORD=root
        cap_add:
            - SYS_NICE
        tmpfs:
            - /var/lib/mysql
        volumes:
            - ./:/usr/evm-plus

networks:
    test-network:
        driver: bridge
