#!/bin/sh

# Check for master branch
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi

# Check for compile errors
if npm run check; then
	# Everything compiles
	:
else
	echo "Compile failure"
	exit 1
fi

# Run tests
if npm test; then
	# We passed
	:
else
	echo "Unit tests have failed"
	exit 1
fi

# Lint code
if node_modules/.bin/tslint --project .; then
	# Code is lint free
	:
else
	echo "Code fails lint check"
	exit 1
fi

# Apply prettier rules
# This now applies the rules instead of checking, as checking was causing issues
#	For some reason, when prettier writes it doesn't necessarily pass its own checks
FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.ts" "*.tsx" | sed 's| |\\ |g')
echo "$FILES" | xargs node_modules/.bin/prettier --write
echo "$FILES" | xargs git add
