/**
 * Copyright (C) 2020 Glenn Rioux
 *
 * This file is part of Event Manager.
 *
 * Event Manager is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Event Manager is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Event Manager.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This array provides all of the currently selectable duty positions within eServices
 */

export const dutyPositions = [
	'Cadet Safety NCO',
	'Cadet Activities NCO',
	'Cadet Activities Officer',
	'Cadet Administrative NCO',
	'Cadet Administrative Officer',
	'Cadet Aerospace Education NCO',
	'Cadet Aerospace Education Officer',
	'Cadet Commander',
	'Cadet Communications NCO',
	'Cadet Deputy Commander for Operations',
	'Cadet Deputy Commander for Support',
	'Cadet Drug Demand Reduction NCO',
	'Cadet Element Leader',
	'Cadet Emergency Services NCO',
	'Cadet Emergency Services Officer',
	'Cadet First Sergeant',
	'Cadet Flight Commander',
	'Cadet Flight Sergeant',
	'Cadet Historian NCO',
	'Cadet Historian Officer',
	'Cadet IT Officer NCO',
	'Cadet IT Officer',
	'Cadet Leadership NCO',
	'Cadet Leadership Officer',
	'Cadet Logistics NCO',
	'Cadet Operations NCO',
	'Cadet Operations Officer',
	'Cadet Public Affairs NCO',
	'Cadet Public Affairs Officer',
	'Cadet Recruiting NCO',
	'Cadet Recruiting Officer',
	'Cadet Safety Officer',
	'Cadet Supply NCO',
	'Cadet Supply Officer',
	'Cadet WCAC Assistant',
	'Cadet WCAC Representative',
	'Activities Officer',
	'Administrative Officer',
	'Advisor to the Commander',
	'Aerospace Education Officer',
	'Alerting Officer',
	'Cadet Activities Officer',
	'Cadet Programs Development Officer',
	'Chaplain',
	'Character Development Instructor',
	'Chief of Staff',
	'CIS Officer',
	'Command NCO',
	'Commander',
	'Communications Engineering Officer',
	'Communications Licensing Officer',
	'Communications Officer ',
	'Communications Training Officer',
	'Counterdrug Officer',
	'Cyber Education Officer',
	'Deputy Commander',
	'Deputy Commander for Cadets',
	'Deputy Commander for Seniors',
	'Director of Administration',
	'Director of Aerospace Education',
	'Director of Cadet Programs',
	'Director of Communications',
	'Director of Development',
	'Director of Education and Training',
	'Director of Emergency Services',
	'Director of Finance',
	'Director of IT',
	'Director of Logistics',
	'Director of Operations',
	'Director of Recruiting',
	'Director of Safety',
	'Disaster Preparedness Officer',
	'Disaster Relief Officer',
	'Diversity Officer',
	'Drug Demand Reduction Officer',
	'Education and Training Officer',
	'Emergency Services Officer',
	'Emergency Services Training Officer',
	'External Aerospace Education Officer',
	'Finance Officer',
	'Fitness Officer',
	'Government Relations Advisor',
	'Health Services Officer',
	'Historian',
	'Homeland Security Officer',
	'Information Technologies Officer',
	'Inspector General',
	'Internal Aerospace Education Officer',
	'Legal Officer',
	'Logistics Officer',
	'Maintenance Officer',
	'Operations Officer',
	'Personnel Officer',
	'Plans and Programs Officer',
	'Public Affairs Officer',
	'Recruiting & Retention Officer',
	'Recruiting Officer',
	'Safety Officer',
	'Search and Rescue Officer',
	'Squadron Activities Officer',
	'Squadron Leadership Officer',
	'Squadron NCO',
	'Standardization/Evaluation Officer',
	'Supply Officer',
	'Testing Officer',
	'Transportation Officer',
	'Vice Commander',
	'Web Security Administrator',
   ];
