#!/bin/sh

# Check for master branch
branch="$(git rev-parse --abbrev-ref HEAD)"

# If the branch is master, higher standards should be enforced,
# while also allowing speedy commits to be made to other branches
if [ "$branch" = "master" ]; then

	# Check for compile errors
	if lerna run check; then
		# Everything compiles
		:
	else
		echo "Compile failure"
		exit 1
	fi

	# Run tests
	# if lerna run test; then
	# 	# We passed
	# 	:
	# else
	# 	echo "Unit tests have failed"
	# 	exit 1
	# fi

	# Lint code
	if lerna run lint; then
		# Code is lint free
		:
	else
		echo "Code fails lint check"
		exit 1
	fi
fi

# Apply prettier rules
# This now applies the rules instead of checking, as checking was causing issues
#	For some reason, when prettier writes it doesn't necessarily pass its own checks
FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.ts" "*.tsx" | sed 's| |\\ |g')
echo "$FILES" | xargs node_modules/.bin/prettier --write
echo "$FILES" | xargs git add
